In [12]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

%matplotlib inline

In [13]:
conda install -c conda-forge/label/main pandas-profiling

Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [14]:
data = pd.read_csv('Demographic_Data.csv')
data.head()

in-store  age  items   amount  region
0         0   37      4   281.03       2
1         0   35      2   219.51       2
2         1   45      3  1525.70       4
3         1   46      3   715.25       3
4         1   33      4  1937.50       1

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   in-store  80000 non-null  int64  
 1   age       80000 non-null  int64  
 2   items     80000 non-null  int64  
 3   amount    80000 non-null  float64
 4   region    80000 non-null  int64  
dtypes: float64(1), int64(4)
memory usage: 3.1 MB


In [17]:
from sklearn.datasets import load_digits
digits = load_digits()

In [18]:
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [19]:
#features
X = data.iloc[:,0:4]
print('Summary of feature sample')
X.head()

Summary of feature sample


in-store  age  items   amount
0         0   37      4   281.03
1         0   35      2   219.51
2         1   45      3  1525.70
3         1   46      3   715.25
4         1   33      4  1937.50

In [20]:
#dependent variable
y = data['region']